### ISSUE TITLE
"FBleaker will extract email from your facebook" and how is that even possible? !

### ISSUE THREAD

**Issue by minanagehsalalma** [ScRiPt1337/FBLeaker#1]

**Comment by ScRiPt1337** [comment]
> _No description provided._

FBLeaker crawler facebook pages thats your friends like and you like and Collact emails from there about pages

**Comment by minanagehsalalma** [comment]
> emails from there about pages

@ScRiPt1337 lol i have never seen pages that provide emails publicly available.

**Comment by ScRiPt1337** [comment]
> > emails from there about pages
> 
> @ScRiPt1337 lol i have never seen pages that provide emails publicly available.

hahaha lol you need eye's doctor then bro  https://www.facebook.com/pg/blackiebumbum/about you will findmany of them in you own profile and friend profile too

**Comment by minanagehsalalma** [comment]
@ScRiPt1337 jokes on you ... you are the one who needs an eye doctor.. this a page email not users email... wtf would a fb page mail do with a user mail that in case if they have liked the page.

**Comment by ScRiPt1337** [comment]
> @ScRiPt1337 jokes on you ... you are the one who needs an eye doctor.. this a page email not users email... wtf would a fb page mail do with a user mail that in case if they have liked the page.

if dont say anywhere that its will going to find user email you need doctor man  seriously

**Comment by minanagehsalalma** [comment]
> that its will going to find user email

@ScRiPt1337  Then explain it !

**Comment by ScRiPt1337** [comment]
> > that its will going to find user email
> 
> @ScRiPt1337 Then explain it !

i mean emails by that maybe i type users my mistake

**Comment by ScRiPt1337** [comment]
> > that its will going to find user email
> 
> @ScRiPt1337 Then explain it !

if admin add it in page its probably going to be his email is most cases and i dont say thats its going to extract user email in readme file

**Comment by minanagehsalalma** [comment]
> > > that its will going to find user email
> > 
> > 
> > @ScRiPt1337 Then explain it !
> 
> if admin add it in page its probably going to be his email not always but in most cases and i dont say thats its going to extract user email in readme file

@ScRiPt1337 lol so you made a script for something that can be done in two clicks ?! That's so funny 😅

**Comment by ScRiPt1337** [comment]
> > > > that its will going to find user email
> > > 
> > > 
> > > @ScRiPt1337 Then explain it !
> > 
> > 
> > if admin add it in page its probably going to be his email not always but in most cases and i dont say thats its going to extract user email in readme file
> 
> @ScRiPt1337 lol so you made a script for something that can be done in two clicks ?! That's so funny sweat_smile

its not going to get email from only page lol hahaha dude you need help bro haha and its  going to check if  there password ever get leak lol i am working on my own colloction of leaked database go and get a life man hahahaha

**Comment by minanagehsalalma** [comment]
@ScRiPt1337 lol on you what would i use the other pages for other than the page i want ? 



> its going to check if there password ever get leak

We can already do that using a single click.

> go and get a life man hahahaha

Haha you is the one who is wasting time on stupid meaningless scripts.

**Comment by ScRiPt1337** [comment]
> @ScRiPt1337 lol on you what would i use the other pages for other than the page i want ?
> 
> > its going to check if there password ever get leak
> 
> We can already do that using a single click.
> 
> > go and get a life man hahahaha
> 
> Haha you is the one who is wasting time on stupid meaningless scripts.

i like to code so i am doing what even i want to code no one asking for your opinion and if you want to get email from  single page then  do it manully maybe you dont knw there is a somethink call Automation  and  hahaha you need a life jealous kid i am doing whatever i want to do
